title: Memory Resident
email: yzure.chen@gmail.com
description: >-
  ijoyc's blog
permalink: date
github_username: ijoyc
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

paginate: 2
paginate_path: "/blog/page:num"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
